name: ChunkAnalysis
main: com.mcmiddleearth.chunkanalysis.ChunkAnalysis
version: 1.1
description: Analysis or modification of chunks in the world
author: Dallen, Eriol_Eandur
depend: [WorldEdit]
softdepend: [MCME-Architect, ResourceRegions]
commands:
  block:
    description: analyse of modify blocks by filter
    usage: see /block help
permissions:
    chunkanalysis.*:
        description: Allows to use all features of ChunkAnalyis plugin
        default: op  
        children:
          chunkanalysis.use: true
          chunkanalysis.developer: true
    chunkanalysis.use:
        description: Allows to use all commands of ChunkAnalysis plugin except /block dev
        default: op  
    chunkanalysis.developer:
        description: Allows to use command /block dev
        default: op  
